local GlobalAddonName, ExRT = ...

if ExRT.locale == "ruRU" then
	return
end

local L = ExRT.L
local PH = ExRT.L --> Promt, Need retranslate

L.message = "Note"
L.marks = "Marks"
L.bossmods = "Bossmods"
L.timers = "Timers"
L.raidcheck = "Raid Check"
L.marksbar = "Marks Bar"
PH.invite = "Invite tools"
L.help = "Help"
L.cd2 = "Raid cooldowns"
L.sooitems = "Raid loot"
L.sallspells = "All Spells"
L.scspells = "Classes"
PH.sencounter = "Encounters statistics"
L.BossWatcher = "Fight log"
L.InspectViewer = "Raid Inspect"
L.Coins = "Bonus Loot"

L.raidtargeticon1 = "{star}"
L.raidtargeticon2 = "{circle}"
L.raidtargeticon3 = "{diamond}"
L.raidtargeticon4 = "{triangle}"
L.raidtargeticon5 = "{moon}"
L.raidtargeticon6 = "{square}"
L.raidtargeticon7 = "{cross}"
L.raidtargeticon8 = "{skull}"

L.messagebutsend = "Send"
L.messagebutclear = "Clear"
PH.messageButCopy = "Move to clean copy, save and send"
L.messagebutfix = "Lock"
PH.messagebutfixtooltip = "Enable resize and move"
L.messagebutalpha = "Alpha"
L.messagebutscale = "Scale"
L.messagebutsendtooltip = "Save and send note to all raid members"
PH.messageOutline = "Text outline"
L.messageBackAlpha = "Background alpha"
L.messageTab1 = "Note"
L.messageTab2 = "Draft"
L.NoteResetPos = "Reset position"
PH.NoteResetPosTooltip = "Move note to center of the screen"
L.NoteColor = "Color"
PH.NoteColorTooltip1 = "Text between the tags |cff00ff00||cXXXXXXXX|r (where XXXXXXXX - color code) and |cff00ff00||r|r will be colored."
PH.NoteColorTooltip2 = "Highlight the text and select a color from the drop down list for coloring."
L.NoteColorRed = "Red"
L.NoteColorGreen = "Green"
L.NoteColorBlue = "Blue"
L.NoteColorYellow = "Yellow"
L.NoteColorPurple = "Purple"
L.NoteColorAzure = "Azure"
L.NoteColorBlack = "Black"
L.NoteColorGrey = "Grey"
L.NoteColorRedSoft = "Soft red"
L.NoteColorGreenSoft = "Soft green"
L.NoteColorBlueSoft = "Soft blue"

L.setminimap1 = "Hide minimap icon"
L.setauthor = "Author"
L.setver = "Version"
L.setcontact = "Contact"
L.setEggTimerSlider = "Global update, ms."
L.SetThanks = "Thanks"
L.YesText = "Yes"
L.NoText = "No"
PH.SetErrorInCombat = "Waiting until combat ends to finish loading."
PH.SetAdditionalTabs = "Additional Tabs"

L.bossmodstot = "Throne of Thunder"
PH.bossmodsradenhelp = "Ra-Den. Left column: 2,4 groups. Right column: 3,5 groups."
L.bossmodsradenonly25 = "Only for 25 ppl raids"
L.bossmodsraden ="Ra-den"
L.bossmodssoo = "Siege of Orgrimmar"
L.bossmodsalpha = "Alpha"
L.bossmodsscale = "Scale"
L.bossmodsclose = "Close all bossmods"
L.bossmodsmalkorok ="Malkorok"
L.bossmodsmalkorokai ="Malkorok AI"
PH.bossmodsmalkorokhelp ="Malkorok bossmod. Left click to choice, right click to cancel."
PH.bossmodsmalkorokaihelp ="Malkorok AI bossmod. Automatic selection with the least amount of people during the AOE. Highlighted in orange for 5 seconds.  Enough to be launched at the same time only one person in the raid with assist."
L.bossmodsmalkorokdanger ="<<< Danger >>>"
L.bossmodsshaofpride = "Norushen / Sha of Pride"
L.bossmodsSpoilsofPandaria = "Spoils of Pandaria"
PH.bossmodsAutoLoadTooltip = "Autoload"
L.bossmodstok = "Thok the Bloodthirsty"
L.BossmodsSpoilsofPandariaMogu = "Mogu"
L.BossmodsSpoilsofPandariaKlaxxi = "Klaxxi"
PH.BossmodsSpoilsofPandariaOpensBox = "opened box on the side:"
L.BossmodsResetPos = "Reset position"
PH.BossmodsResetPosTooltip = "Move all frames-bossmods to center of the screen"
L.BossmodsMalkorokSkada = "Malkorok Skada"
PH.BossmodsMalkorokSkadaTooltip = "Module for Skada addon. Displays effective healing"
L.BossmodsMalkorokSkadaError1 = "Skada not found"
L.BossmodsMalkorokSkadaError2 = "Module already loaded"
L.BossmodsMalkorokSkadaOnLoad1 = "Module \"Malkorok Skada\" loaded!"
PH.BossmodsMalkorokSkadaOnLoad2 = "Attention! To disable the module \"Malkorok Skada\" you must reload UI with chat command \"/reload\""

PH.timerstxt1 = "/rt pull\n/rt pull X\n/rt afk X\n/rt afk 0\n/rt timer S X\n|cFFFFFFFF |r\n\n\n/rt mytimer X"
PH.timerstxt2 = "- pull timer, 10 seconds\n- pull timer, X seconds\n- afk (break) timer, X minutes\n- cancel afk timer\n- run timer with name \"S\" with duration X seconds\n\n\n\n- countdown on combat timer, X seconds"
L.timerattack = "Pull"
L.timerattackcancel = "CANCELED"
L.timerattackt = "Pull in"
L.timerafk = "Break"
L.timerafkcancel = "Break canceled"
L.timermin = "min."
L.timersec = "sec."
L.timerTimerFrame = "Combat timer"
PH.TimerTimeToKill = "Time to target killing"

L.raidchecknofood = "No food"
PH.raidchecknoflask = "No flask"
L.raidcheckfood = "Check food"
PH.raidcheckfoodchat = "Food report to chat"
PH.raidcheckflask = "Check flask"
PH.raidcheckflaskchat = "Flask report to chat"
PH.raidcheckslak = "Food and Flask report on ready check"
L.raidcheckPotion = "Potions: "
L.raidcheckHS = "Health stones: "
PH.raidcheckPotionCheck = "Enable tracking potions and health stones"
PH.raidcheckPotionLastPull = "Potions for last fignt"
PH.raidcheckPotionLastPullToChat = "Potions report to chat"
PH.raidcheckHSLastPull = "Health stones for last fignt"
PH.raidcheckHSLastPullToChat = "Health stones report to chat"
L.raidcheckReadyCheck = "Ready Check"
L.raidcheckReadyCheckScale = "Scale"
L.raidcheckReadyCheckTest = "Test"
PH.raidcheckReadyCheckTimerTooltip = "Disappearance time after the ready check (in seconds):"
L.raidcheckReadyCheckSec = "sec."

L.marksbarstart = "Clear"
L.marksbardel = "Delete"
L.marksbarrc = "Ready"
L.marksbarpull = "Pull"
PH.marksbarshowmarks = "Show marks"
PH.marksbarshowpermarks = "Show permamarks"
PH.marksbarshowfloor = "Show world marks"
PH.marksbarshowrcpull = "Show ready check and pull buttons"
L.marksbaralpha = "Alpha"
L.marksbarscale = "Scale"
PH.marksbartmr = "Pull timer, sec.:"
PH.marksbarWMView = "Marks form:"
L.MarksBarResetPos = "Reset position"
PH.MarksBarResetPosTooltip = "Move frame to center of the screen"

L.inviterank = "Rank:"
L.inviteinv = "Invite"
PH.inviteguildonly = "Invite only guild members"
PH.invitewords = "Invite by keywords in whispers"
PH.invitewordstooltip = "Keywords"
PH.invitedis = "Disband raid"
PH.inviteReInv = "Disband and Reinvite raid"
L.inviteaccept = "Autoaccept invite from my friends and guild members"
PH.inviteAutoPromote = "Autopromote"
PH.inviteAutoPromoteTooltip = "Names for autopromote"
PH.inviteAutoPromoteDontUseGuild = "Do not use"
--L.inviteHelpRaid = "Общее управление рейдом. В выпадающем списке выбирается минимальное звание для автоприглашений. Все игроки, находящиеся в нем или выше будут приглашены в рейд после нажатия кнопки \"".. --L.inviteinv .."\". Так же можно распустить рейд или пересобрать его в течении 5 секунд."
--L.inviteHelpAutoInv = "Приглашение в группу или рейд игроков, которые напишут вам в приватные сообщения любую из ключевых фраз, которые задаются в поле для ввода"
--L.inviteHelpAutoAccept = "Автоматическое мгновенное принятие приглашений в группу или рейд"
--L.inviteHelpAutoPromote = "Функция для рейд-лидера. Автоматическое повышение звания в рейде до помощника игрокам с выбранными никами или находящихся в гильдии в звании, выбранном в выпадающем списке, или выше."
L.inviteRaidDemote = "Demote everyone"

L.cd2fix = "Lock"
L.cd2alpha = "Alpha"
L.cd2scale = "Scale"
PH.cd2lines = "Lines"
L.cd2split = "Split columns"
PH.cd2splittooltip = "Split each column on a separate independent window"
L.cd2width = "Width"
PH.cd2graytooltip = "Gray icons"
PH.cd2noraid = "Show off raid"
L.cd2Spells = "Spells"
PH.cd2Appearance = "Appearance"
PH.cd2PriorityTooltip = "Lower number = higher priority"
PH.cd2ColNum = "Column number"
L.cd2Priority = "Priority"
L.cd2SpellID = "Spell ID"
L.cd2EditBoxCDTooltip = "CD, sec."
L.cd2EditBoxDurationTooltip = "Duration, sec."
L.cd2Class = "Class"
L.cd2Spec = "Specialization"
L.cd2RemoveButton = "Remove"
L.cd2AddSpell = "Add Spell"
PH.cd2AddSpellFromList = "Add Spell from list"
L.cd2AddSpellFrameName = "Spells list"
L.cd2AddSpellFrameCDText = "CD"
L.cd2AddSpellFrameDurationText = "duration"
L.cd2AddSpellFrameColumnText = "Column"
L.cd2AddSpellFrameTalent = "Talent"
PH.cd2AddSpellFrameDuration = "Duration changed by"
PH.cd2AddSpellFrameCDChange = "Cooldown changed by"
PH.cd2AddSpellFrameCharge = "Has charges"
PH.cd2AddSpellFrameChargeChange = "Gets charges through"
PH.cd2AddSpellFrameCast = "Displayed while casting"
PH.cd2AddSpellFrameDurationLost = "Duration canceled with aura"
PH.cd2AddSpellFrameSharing = "Shared cooldown with"
PH.cd2AddSpellFrameDispel = "Dispel"
PH.cd2AddSpellFrameReplace = "Ceases unavailable by using talent"
L.cd2AddSpellFrameRadiness = "Readiness"
PH.cd2ButtonModify = "Change >>"
L.cd2TextSpell = "Spell"
L.cd2TextAdd = "Add"
PH.cd2ColSet = "Columns setup"
PH.cd2ColSetBotToTop = "Upwards"
PH.cd2ColSetGeneral = "Use common settings"
PH.cd2ColSetResetPos = "Reset position"
L.cd2ColSetTextRight = "Right text"
L.cd2ColSetTextCenter = "Center text"
L.cd2ColSetTextLeft = "Left text"
PH.cd2ColSetTextReset = "Reset to default"
PH.cd2ColSetTextTooltip = "Use these templates in the text boxes above:|n|cff00ff00%name%|r - player name|n|cff00ff00%time%|r - cooldown|n|cff00ff00%name_time%|r - player name. If on cd, then time|n|cff00ff00%spell%|r - spell name|n|cff00ff00%stime%|r - \"short time\".|n|cff00ff00%name_stime%|r - player name. If on cd, then \"short time\"|n|cff00ff00%status%|r - text status if player dead/offline"
PH.cd2ColSetMethodCooldown = "Cooldown animation for icon"
L.cd2ColSetTextIconName = "Player name on spell icon"
PH.cd2ColSetColsInCol = "Number of lines in a row"
PH.cd2GeneralSet = "General setup"
L.cd2GeneralSetTestMode = "Test Mode"
PH.cd2OtherSet = "Other setup"
L.cd2OtherSetTexture = "Texture"
L.cd2OtherSetColor = "Set Colors"
PH.cd2OtherSetColorFrameText = "Standart color"
PH.cd2OtherSetColorFrameActive = "Active color"
PH.cd2OtherSetColorFrameCooldown = "Unavailable color"
PH.cd2OtherSetColorFrameCast = "Cast color"
PH.cd2OtherSetColorFrameAlpha = "Backgroung alpha"
PH.cd2OtherSetColorFrameAlphaCD = "Time line alpha"
PH.cd2OtherSetColorFrameAlphaCooldown = "Unavailable alpha"
PH.cd2OtherSetColorFrameReset = "Reset to default"
PH.cd2OtherSetColorFrameSoften = "Soften colors"
PH.cd2OtherSetColorFrameClass = "Use class color"
PH.cd2OtherSetColorFrameTopText = "Text"
PH.cd2OtherSetColorFrameTopBack = "Back"
PH.cd2OtherSetColorFrameTopTimeLine = "Line"
L.cd2OtherSetIconSize = "Icon Size"
L.cd2OtherSetFontSize = "Font Size"
L.cd2OtherSetFont = "Font"
PH.cd2OtherSetOutline = "Font outline"
L.cd2OtherSetFontShadow = "Font Shadow"
PH.cd2OtherSetAnimation = "Enable animation"
L.cd2OtherSetReset = "Reset"
PH.cd2OtherSetOnlyOnCD = "Show only on cd"
PH.cd2OtherSetIconPosition = "Icon Position"
PH.cd2OtherSetIconPositionLeft = "Icon Left"
PH.cd2OtherSetIconPositionRight = "Icon Right"
PH.cd2OtherSetIconPositionNo = "Hide Icon"
PH.cd2OtherSetStyleAnimation = "Style Animation"
L.cd2OtherSetStyleAnimation1 = "Starts Full"
L.cd2OtherSetStyleAnimation2 = "Starts Empty"
PH.cd2OtherSetTimeLineAnimation = "Available line"
PH.cd2OtherSetTimeLineAnimation1 = "Do not fill with time line"
PH.cd2OtherSetTimeLineAnimation2 = "Fill with time line"
L.cd2OtherSetTabNameGeneral = "General"
L.cd2OtherSetTabNameIcons = "Icons"
L.cd2OtherSetTabNameColors = "Textures and Colors"
L.cd2OtherSetTabNameFont = "Font"
L.cd2OtherSetTabNameText = "Name and Time"
PH.cd2OtherSetTabNameOther = "Other setup"
L.cd2OtherSetTabNameTemplate = "Templates"
PH.cd2OtherSetTemplateRestore = "Restore"
PH.cd2fastSetupTitle = "Fast Setup"
L.cd2fastSetupTooltip = "Spells list"
PH.cd2fastSetupTitle1 = "Raid CD's"
PH.cd2fastSetupTitle2 = "Direct CD's"
L.cd2fastSetupTitle3 = "Resurrections"
L.cd2fastSetupTitle4 = "Interrupts"
L.cd2fastSetupTitle5 = "Taunts"
L.cd2fastSetupTitle6 = "Dispels"
PH.cd2History = "History"
L.cd2HistoryClear = "Clear"
PH.cd2HelpFastSetup = "Quick start! Turn on module, move frame with cooldowns to the desired location and don't forget to fixate it. Use buttons of \"Fast Setup\" for adding spells."
PH.cd2HelpOnOff = "Enable spells to start tracking"
PH.cd2HelpCol = "Select the class"
PH.cd2HelpPriority = "Select priority. Spell with lowest priority number will be shown above the rest"
PH.cd2HelpTime = "Set cooldown, duration and column. (* You can't change CD and duration for base spells)"
PH.cd2HelpColSetup = "Personal settings for each column. Don't forget to \"enable\" them."
PH.cd2HelpTestButton = L.cd2GeneralSetTestMode
PH.cd2HelpButtonDefault = "Reset all settings for selected column to defaults"
PH.cd2HelpAddButton = "Add custom spells. Scroll page down and click \"".. L.cd2AddSpell .."\". Set spell ID in first edit box, select the class, and then press button \"".. L.cd2ButtonModify .."\" for change CD, duration and column."
PH.cd2HelpHistory = "History of usage all spells."
PH.cd2ColSetFontOtherAvailable = "Settings for each text position"
L.cd2ColSetFontPosGeneral = "General"
L.cd2ColSetFontPosLeft = "Left"
L.cd2ColSetFontPosRight = "Right"
L.cd2ColSetFontPosCenter = "Center"
L.cd2ColSetFontPosIcon = "Icon"
PH.cd2ColSetBetweenLines = "Indents between lines"
L.cd2BlackBack = "Background alpha"
L.cd2StatusOffline = "(offline)"
L.cd2StatusDead = "(dead)"
L.cd2InspectHaste = "%+(%d+) Haste"
L.cd2InspectHasteGem = "NOT USABLE IN THIS LOCALE"
L.cd2InspectMastery = "%+(%d+) Mastery"
L.cd2InspectMasteryGem = "NOT USABLE IN THIS LOCALE"
L.cd2InspectCrit = "%+(%d+) Critical Strike"
L.cd2InspectCritGem = "NOT USABLE IN THIS LOCALE"
L.cd2InspectCritGemLegendary = "%+%]%](%d+) Crit,"
L.cd2InspectSpirit = "%+(%d+) Spirit"
L.cd2InspectInt = "%+(%d+) Intellect"
L.cd2InspectIntGem = "NOT USABLE IN THIS LOCALE" -- Legendary
L.cd2InspectStr = "%+(%d+) Strength"
L.cd2InspectStrGem = "NOT USABLE IN THIS LOCALE"
L.cd2InspectAgi = "%+(%d+) Agility"
L.cd2InspectSpd = "%+(%d+) Spell Power"
L.cd2InspectAll = "%+(%d+) All Stats"
L.cd2OtherSetBorder = "Border"
PH.cd2OtherSetIconToolip = "Tooltip for icon on hover"
PH.cd2OtherSetLineClick = "Send message to chat on click"

L.sallspellsEggClear = "Clear"
L.sallspellsEgg = "Combat log"
PH.sallspellsEggPlayers = "Record players"
L.sallspellsEggAutoLoad = "Autoload"

L.sooitemssooboss1 = "Immerseus"
L.sooitemssooboss2 = "The Fallen Protectors"
L.sooitemssooboss3 = "Norushen"
L.sooitemssooboss4 = "Sha of Pride"
L.sooitemssooboss5 = "Galakras"
L.sooitemssooboss6 = "Iron Juggernaut"
L.sooitemssooboss7 = "Kor'kron Dark Shaman"
L.sooitemssooboss8 = "General Nazgrim"
L.sooitemssooboss9 = "Malkorok"
L.sooitemssooboss10 = "Spoils of Pandaria"
L.sooitemssooboss11 = "Thok the Bloodthirsty"
L.sooitemssooboss12 = "Siegecrafter Blackfuse"
L.sooitemssooboss13 = "Paragons of the Klaxxi"
L.sooitemssooboss14 = "Garrosh Hellscream"
L.sooitemstotboss1 = "Jin'rokh the Breaker"
L.sooitemstotboss2 = "Horridon"
L.sooitemstotboss3 = "Council of Elders"
L.sooitemstotboss4 = "Tortos"
L.sooitemstotboss5 = "Megaera"
L.sooitemstotboss6 = "Ji-Kun"
L.sooitemstotboss7 = "Durumu the Forgotten"
L.sooitemstotboss8 = "Primordius"
L.sooitemstotboss9 = "Dark Animus"
L.sooitemstotboss10 = "Iron Qon"
L.sooitemstotboss11 = "Twin Consorts"
L.sooitemstotboss12 = "Lei Shen"
L.sooitemstotboss13 = "Ra-den"
L.sooitemstrash = "Trash"
L.sooitemssets = "Sets"
L.sooitemst15 = "Throne of Thunder"
L.sooitemst16 = "Siege of Orgrimmar"

L.sencounterUnknown = "unknown"
L.sencounter5ppl = "5 players"
L.sencounter5pplHC = "5 players heroic"
L.sencounter10ppl = "10 players"
L.sencounter25ppl = "25 players"
L.sencounter10pplHC = "10 players heroic"
L.sencounter25pplHC = "25 players heroic"
L.sencounterLfr = "Raid Finder"
L.sencounterChall = "Challenge mode"
L.sencounter40ppl = "40 players"
L.sencounter3pplHC = "Heroic scenario"
L.sencounter3ppl = "Scenario"
L.sencounterFlex = "Flexible Raid"
L.sencounterMystic = "Mythic *"
L.sencounterWODNormal = "Normal mode"
L.sencounterWODHeroic = "Heroic mode"
L.sencounterWODMythic = "Mythic mode"
L.sencounterBossName = "Boss name"
L.sencounterFirstKill = "FK"
L.sencounterWipes = "Pulls"
L.sencounterKills = "Kills"
L.sencounterFirstBlood = "First Blood"
L.sencounterWipeTime = "Wipe"
L.sencounterKillTime = "Kill"
L.sencounterOnlyThisChar = "Only This Char"
L.EncounterClear = "Clear all data"
L.EncounterClearPopUp = "All data will be lost. Are you sure?"

L.BossWatcherFilterTaunts = "Taunts"
L.BossWatcherFilterOnlyBuffs = "Only Buffs"
L.BossWatcherFilterOnlyDebuffs = "Only Debuffs"
L.BossWatcherFilterBySpellID = "Spell ID:"
L.BossWatcherFilterLagFix = "Lag Fix"
L.BossWatcherFilterTooltip = "Spells list"
L.BossWatcherFilterStun = "Stuns"
PH.BossWatcherFilterPersonal = "Protective"
L.BossWatcherChkShowGUIDs = "Show unique ID"
L.BossWatcherTabMobs = "Damage"
L.BossWatcherTabInterruptAndDispel = "Interrupts and Dispels"
L.BossWatcherTabBuffsAndDebuffs = "Buffs and Debuffs"
L.BossWatcherTabBuffsAndDebuffsTooltip = "Buffs and Debuffs"
L.BossWatcherReportTotal = "Total"
L.BossWatcherReportCast = "By cast"
L.BossWatcherReportSwitch = "By target"
L.BossWatcherDamageSwitchTabDamage = "Damage"
L.BossWatcherDamageSwitchTabSwitch = "Switch time"
L.BossWatcherDamageSwitchTabInfo = "Info"
L.BossWatcherDamageSwitchTabInfoNoInfo = "No Info"
L.BossWatcherDamageSwitchTabInfoRIP = "R.I.P."
L.BossWatcherInterrupts = "Interrupts"
L.BossWatcherDispels = "Dispels"
L.BossWatcherBuffsAndDebuffsTextOn = "on"
L.BossWatcherBuffsAndDebuffsTooltipTitle = "Events"
L.BossWatcherBuffsAndDebuffsFilterSource = "Source"
L.BossWatcherBuffsAndDebuffsFilterTarget = "Target"
L.BossWatcherBuffsAndDebuffsFilterAll = "all"
L.BossWatcherBuffsAndDebuffsFilterFriendly = "friendly"
L.BossWatcherBuffsAndDebuffsFilterHostile = "hostile"
L.BossWatcherBuffsAndDebuffsFilterSpecial = "Special"
L.BossWatcherBuffsAndDebuffsFilterClear = "Clear filter"
L.BossWatcherBuffsAndDebuffsFilterNone = "None"
L.BossWatcherBuffsAndDebuffsFilterFilter = "Filter"
L.BossWatcherBuffsAndDebuffsTooltipCountText = "Count"
L.BossWatcherBuffsAndDebuffsTooltipUptimeText = "Uptime"
L.BossWatcherUnknown = "Unknown"
L.BossWatcherLastFight = "Last Fight"
L.BossWatcherTimeLineTooltipTitle = "Events"
L.BossWatcherTimeLineCast = "cast"
L.BossWatcherTimeLineCastStart = "begin cast"
L.BossWatcherTimeLineDies = "dies"
L.BossWatcherTimeLineOnText = "on"
L.BossWatcherInterruptText = "interrupt"
L.BossWatcherByText = "with"
L.BossWatcherDispelText = "dispel"
L.BossWatcherToChat = "Send to chat"
L.BossWatcherClear = "Clear"
L.BossWatcherSegments = "Segments"
PH.BossWatcherSegmentsTooltip = "To start new segment during combat type in the chat command \"/rt seg\".\n\nAlso You can configure the automatic start of the new segments."
PH.BossWatcherSegmentEventsUSS = "Spell Cast Success"
PH.BossWatcherSegmentEventsSAR = "Aura Removed"
PH.BossWatcherSegmentEventsSAA = "Aura Applied"
PH.BossWatcherSegmentEventsUD = "NPC dies"
PH.BossWatcherSegmentEventsCMRBE = "Chat message about the ability of the boss"
L.BossWatcherSegmentNamesUSS = "Spell"
L.BossWatcherSegmentNamesSAA = "+ aura"
L.BossWatcherSegmentNamesSAR = "- aura"
L.BossWatcherSegmentNamesUD = "Death"
L.BossWatcherSegmentNamesES = "Combat"
L.BossWatcherSegmentNamesSC = "Chat command"
L.BossWatcherSegmentNamesCMRBE = "Chat message"
L.BossWatcherSegmentsSpellTooltip = "Spell ID or NPC ID"
L.BossWatcherSegmentSelectAll = "Select all"
L.BossWatcherSegmentSelectNothing = "Select nothing"
L.BossWatcherFilterBySpellName = "Spell Name:"
L.BossWatcherSendToChat = "Send To Chat"
PH.BossWatcherOverkills = "Fatality Damage"
L.BossWatcherOverkillText = "kills"
L.BossWatcherOverkillWithText = "with"
PH.BossWatcherOverkillOnText = "O:"
L.BossWatcherPetOwner = "%s's pet"
PH.BossWatcherDoNotReset = "Do not reset"
PH.BossWatcherDoNotResetTooltip = "Do not reset data after combat start."
L.BossWatcherPetText = "Pet"
PH.BossWatcherMarkOnDeath = "Mark on death"
L.BossWatcherSegmentClear = "Clear"
PH.BossWatcherSegmentPreSet = "Pre Set"
L.BossWatcherOptions = "Other settings"
L.BossWatcherOptionsFightsSave = "Save fights:"
PH.BossWatcherOptionsFightsWarning = "* Big number requires more resources"
L.BossWatcherSelectFight = "Select fight"
L.BossWatcherSelectFightClose = "Close"
PH.BossWatcherChatSpellMsg = "Chat message about spell"
L.BossWatcherFilterPotions = "Potions"
PH.BossWatcherFilterRaidSaves = "Raid cooldowns"
L.BossWatcherFilterPandaria = "Pandaria: legendary"
L.BossWatcherFilterTier16 = "Siege of Orgrimmar"
PH.BossWatcherOptionSpellID = "Show spells ID for time line"
L.BossWatcherTabPlayersSpells = "Players spells"
L.BossWatcherTabPlayersSpellsTooltip = ""
PH.BossWatcherDamageBoxPlayerTooltip = "Click for damage by spell info"
PH.BossWatcherSegmentNowTooltip = "Spell now:"
L.BossWatcherTabHeal = "Healing"
L.BossWatcherTabInterruptAndDispelShort = "Interrupts,Dispels"
L.BossWatcherHealBySource = "By Source"
L.BossWatcherHealByTarget = "By Target"
L.BossWatcherHealAllSourceText = "All Sources"
L.BossWatcherHealAllTargetText = "All Targets"
PH.BossWatcherErrorInCombat = "Waiting until combat ends for update data."
PH.BossWatcherTabEnergy = "Power"
L.BossWatcherEnergyOnce1 = "times"
L.BossWatcherEnergyOnce2 = "times"
L.BossWatcherEnergyType0 = "Mana"
L.BossWatcherEnergyType1 = "Rage"
L.BossWatcherEnergyType2 = "Focus"
L.BossWatcherEnergyType3 = "Energy"
L.BossWatcherEnergyType5 = "Runes"
L.BossWatcherEnergyType6 = "Runic power"
L.BossWatcherEnergyType7 = "Soul shards"
L.BossWatcherEnergyType8 = "Eclipse"
L.BossWatcherEnergyType9 = "Holy Power"
L.BossWatcherEnergyType10 = "Alternate Power"
L.BossWatcherEnergyType12 = "Chi"
L.BossWatcherEnergyType13 = "Shadow orbs"
L.BossWatcherEnergyType14 = "Burning Embers"
L.BossWatcherEnergyType15 = "Demonic Fury"
L.BossWatcherEnergyTypeUnknown = "Power ID: "

L.InspectViewerTalents = "Talents and glyps"
L.InspectViewerInfo = "Other info"
L.InspectViewerItems = "Equipment"
L.InspectViewerNoData = "No data"
PH.InspectViewerEnabledTooltip = "Can't disable, when \""..L.cd2.."\" enabled"
L.InspectViewerRadiness = "Radiness"
L.InspectViewerRaidIlvl = "Raid Item Level"
PH.InspectViewerRaidIlvlData = "players: %d"
L.InspectViewerHaste = "Haste"
L.InspectViewerMastery = "Mastery"
L.InspectViewerCrit = "Crit."
L.InspectViewerSpirit = "Spirit"
L.InspectViewerInt = "Intellect"
L.InspectViewerStr = "Strength"
L.InspectViewerAgi = "Agility"
L.InspectViewerSpd = "Spell Power"

L.CoinsSpoilsOfPandariaWinTrigger = "System resetting. Don't turn the power off, or the whole thing will probably explode."
PH.CoinsEmpty = "Empty yet"
PH.CoinsHelp = "History of raid's bonus rolls and loots"
L.CoinsClear = "Clear all data"
L.CoinsClearPopUp = "All data will be lost. Are you sure?"

L.senable = "Enable"

L.minimaptooltiplmp = "Left Click - move"
L.minimaptooltiprmp = "Right Click - open menu"
L.minimaptooltipfree = "Shift+Alt+Left Click - free move"
L.minimapmenu = "Menu ExRT"
L.minimapmenuset = "Settings"
L.minimapmenuclose = "Close"

L.classLocalizate = {
	["WARRIOR"] = "Warrior",
	["PALADIN"] = "Paladin",
	["HUNTER"] = "Hunter",
	["ROGUE"] = "Rogue",
	["PRIEST"] = "Priest",
	["DEATHKNIGHT"] = "Death Knight",
	["SHAMAN"] = "Shaman",
	["MAGE"] = "Mage",
	["WARLOCK"] = "Warlock",
	["MONK"] = "Monk",
	["DRUID"] = "Druid",
	["PET"] = "Pets",
}

L.specLocalizate = {
	["MAGEDPS1"] = "Arcane",
	["MAGEDPS2"] = "Fire",
	["MAGEDPS3"] = "Frost",
	["PALADINHEAL"] = "Holy",
	["PALADINTANK"] = "Protection",
	["PALADINDPS"] = "Retribution",
	["WARRIORDPS1"] = "Arms",
	["WARRIORDPS2"] = "Fury",
	["WARRIORTANK"] = "Protection",
	["DRUIDDPS1"] = "Balance",
	["DRUIDDPS2"] = "Feral",
	["DRUIDTANK"] = "Guardian",
	["DRUIDHEAL"] = "Restoration",
	["DEATHKNIGHTTANK"] = "Blood",
	["DEATHKNIGHTDPS1"] = "Frost",
	["DEATHKNIGHTDPS2"] = "Unholy",
	["HUNTERDPS1"] = "Beast Mastery",
	["HUNTERDPS2"] = "Marksmanship",
	["HUNTERDPS3"] = "Survival",
	["PRIESTHEAL1"] = "Discipline",
	["PRIESTHEAL2"] = "Holy",
	["PRIESTDPS"] = "Shadow",
	["ROGUEDPS1"] = "Assassination",
	["ROGUEDPS2"] = "Combat",
	["ROGUEDPS3"] = "Subtlety",
	["SHAMANDPS1"] = "Elemental",
	["SHAMANDPS2"] = "Enhancement",
	["SHAMANHEAL"] = "Restoration",
	["WARLOCKDPS1"] = "Affliction",
	["WARLOCKDPS2"] = "Demonology",
	["WARLOCKDPS3"] = "Destruction",
	["MONKTANK"] = "Brewmaster",
	["MONKDPS"] = "Windwalker",
	["MONKHEAL"] = "Mistweaver",
	["NO"] = "All specializations",
}

L.creatureNames = {	--> Used LibBabble-CreatureType and WowHead
	Abyssal = "Abyssal",
	Basilisk = "Basilisk",
	Bat = "Bat",
	Bear = "Bear",
	Beast = "Beast",
	Beetle = "Beetle",
	["Bird of Prey"] = "Bird of Prey",
	Boar = "Boar",
	["Carrion Bird"] = "Carrion Bird",
	Cat = "Cat",
	Chimaera = "Chimaera",
	["Core Hound"] = "Core Hound",
	Crab = "Crab",
	Crane = "Crane",
	Critter = "Critter",
	Crocolisk = "Crocolisk",
	Demon = "Demon",
	Devilsaur = "Devilsaur",
	Direhorn = "Direhorn",
	Dog = "Dog",
	Doomguard = "Doomguard",
	Dragonhawk = "Dragonhawk",
	Dragonkin = "Dragonkin",
	Elemental = "Elemental",
	Felguard = "Felguard",
	Felhunter = "Felhunter",
	["Fel Imp"] = "Fel Imp",
	Fox = "Fox",
	["Gas Cloud"] = "Gas Cloud",
	Ghoul = "Ghoul",
	Giant = "Giant",
	Goat = "Goat",
	Gorilla = "Gorilla",
	Humanoid = "Humanoid",
	Hyena = "Hyena",
	Imp = "Imp",
	Mechanical = "Mechanical",
	Monkey = "Monkey",
	Moth = "Moth",
	["Nether Ray"] = "Nether Ray",
	["Non-combat Pet"] = "Non-combat Pet",
	["Not specified"] = "Not specified",
	Observer = "Observer",
	Porcupine = "Porcupine",
	Quilen = "Quilen",
	Raptor = "Raptor",
	Ravager = "Ravager",
	["Remote Control"] = "Remote Control",
	Rhino = "Rhino",
	Scorpid = "Scorpid",
	Serpent = "Serpent",
	["Shale Spider"] = "Shale Spider",
	Shivarra = "Shivarra",
	Silithid = "Silithid",
	Spider = "Spider",
	["Spirit Beast"] = "Spirit Beast",
	Sporebat = "Sporebat",
	Succubus = "Succubus",
	Tallstrider = "Tallstrider",
	Terrorguard = "Terrorguard",
	Totem = "Totem",
	Turtle = "Turtle",
	Undead = "Undead",
	Voidlord = "Voidlord",
	Voidwalker = "Voidwalker",
	["Warp Stalker"] = "Warp Stalker",
	Wasp = "Wasp",
	["Water Elemental"] = "Water Elemental",
	["Water Strider"] = "Water Strider",
	["Wind Serpent"] = "Wind Serpent",
	Wolf = "Wolf",
	Worm = "Worm",
	Wrathguard = "Wrathguard",
	[1] = "Tenacity",
	[2] = "Cunning",
	[3] = "Ferocity",
}